### ISSUE TITLE
Parse error for a.1.2 which parses as a.12

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#156]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/156/) on Sourceforge by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-07 08:36:02.271000:

For some reason the parser reads a.1.2 as being a.12 where it only has a single parameter that gets the value of 1 concatenated with 2.

observed in [1f663e5fd37c2c866d8be54796e3296daf4d50a4]

**Comment by lausdahl** [comment]
A full model looks like:

```
process

 P =

begin

 @ a.1.2 -> Skip

end
```

This appears to have been fixed by #199
