### ISSUE TITLE
Are you allowed to write to a state component even though its not specified in the nameset?

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#179]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/179/) on Sourceforge by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-12-03 13:21:22.361000:

Example code:

```
channels 
a
b : int

process A = 
begin
    state
        v : int := 0

    @ (a -> v := 1 [| {v} | {| a |} | {} |] a-> v := 2) ; b.(v) -> Skip
end
```

**Comment by alvarohm** [comment]
I don't know if this question has been answered or not, but I believe that you are allowedto write to a state component not in the specified nameset, however, that update is lost after the parallellism terminate. Essentially, the two parallel actions are executed in local copies of the state, and once the parallelism terminates, the local states are merged according to the name set partition to form the new state.

**Comment by joey-coleman** [comment]
Implementation conforms to this.
