### ISSUE TITLE
IDE does not make enum types bold

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#181]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/181/) on Sourceforge by [ldcouto](https://sourceforge.net/u/ldcouto/profile/), 2013-12-04 14:39:24.163000:

Bit of a minor thing. Only seems to happen in communications.

chan!**<enum\>** has the nice effect.

chan.<enum\> does not.

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/181/#e51f) by [ldcouto](https://sourceforge.net/u/ldcouto/profile/), 2013-12-04 15:52:44.112000:
- **summary**: IDe does not make enum types bold --> IDE does not make enum types bold

**Comment by lausdahl** [comment]
This is fixed in [58b16552639e2d8d7bbdee701b87dc94ff9642ec]
