### ISSUE TITLE
Errors should be sortable by order in file

### ISSUE THREAD

**Issue by RalphHains** [symphonytool/symphony#198]
Because the "Location" says things like "line: 309" the leading "line:" means it is text and so if you use this field to sort it is sorted alphabetically not numerically  (which might result in an order like "1, 10, 101, 2, 22" you get my drift?. I am not quite sure if this  qualifies as a bug or an enhancement request (somewhere in the middle?) and I wouldn't put it all that high (more an annoyance). I'll label as bug but feel free to change
It only really starts to have an effect once there are no syntax errors (as only the first syntax error is reported per file) but once the type checker is run it shows!

**Comment by lausdahl** [comment]
The bug needs a more detailed description. What Errors and what locations are we talking about. Also where are these shown and what reports them.

Please provide more info and a test model that shown this. If this is related to GUI then also show a picture to illustrate.

**Comment by RalphHains** [comment]
This is where either GIT or my knowledge of it makes things hard - how do I attach a screenshot or a file?
I'll try again textually. Symphony has a Tab "Problems" that is used to list Errors and Warnings as a table. The table has a column "Location" that gives line numbers. As expected clicking the column performs a sort based on the cell contents in that column. But not (as expected) numerically based on the line number - instead an alpha sort results - which puts "line 10" before "line 2". Implemented as a numeric sort based on line number the capability would be useful - as an alpha sort it isn't useful (it is inappropriate) . To reproduce you need a cml file with typecheck errors (or any errors showing after the typechecker is run) at lines 2 and 10, but if you still need an example from me to illustrate it let me know how to post it and I will (or I could email it to you?)

**Comment by lausdahl** [comment]
Here is an example that shown how the errors are sorted in the Problems view when selecting sort by the Location column:

```
class bug198 = begin values -- line 1
f:int ='m'







g:int =3.4











h:int =3.4
end
```

Note that Line: 2 comes after Line: 10 but before Line: 22. The expected order was 2, 10, 22.
![image](https://cloud.githubusercontent.com/assets/2575418/2719165/057479c4-c55c-11e3-888a-837c7bcd9021.png)

**Comment by RalphHains** [comment]
Thank you Kenneth – this will help me posting SysML2CML bugs for Alvaro too! Hopefully it is a straightforward as it seems in the video!

Ralph

**Comment by RalphHains** [comment]
I can't help thinking that if you could prevent the leading "line: " that eclipse might sort numerically. I guess if you are right it is a problem in Eclipse not Symphony but it does surprise me - it is always useful to know the first error encountered (strictly speaking first matters more than highest in file, but more often than not they are the same thing - algorithms don't often backtrack. Otherwise time and effort is spent trying to fix "ghost" problems, rather than the fundamentals. Another possibility would be a way to turn off the sort (then presumably the errors would come out in creation order). But in common with many similar widget implementations there doesn't seem to be a way to turn off a sort once one is active (only to replace it with a different one)

**Comment by lausdahl** [comment]
I looked at the internals of JDT and check how it worked in from the users perspective. It turns out that it in fact works as you want it too. The odd thing is just that it seems like we do exactly the same in Symphony but yet it doesn't work for us. I wont spent more time looking at it now, but keep it in mind (maybe I get an idea to why it works for JDT).
