### ISSUE TITLE
Parser error for decimal numbers when using e.g. Danish locale 3.123 = 31234

### ISSUE THREAD

**Issue by lausdahl** [symphonytool/symphony#199]
The decimal parser used within the parser depends on the current locale to interpret decimal numbers. This makes it possible to change the meaning of the number 3.123 to 3123 when using a Danish number format where a comma ',' is used for decimal numbers and not a '.'.

**Comment by joey-coleman** [comment]
Nice catch of the root problem to this and #156 – I tend to be blind to locales.
