### ISSUE TITLE
The renaming actions with binding and predicate does not have any semantics defined

### ISSUE THREAD

**Issue by lausdahl** [symphonytool/symphony#201]
The following process uses a renaming action that is not defined in the semantics document. Therefore it is not possible to type check the node.

```
process RegisterProc = 
 begin
   @
     A[[e <- x.e | e in set I @ test]]
 end
```

**Comment by lausdahl** [comment]
The node will be marked as unsupported in a future version of the type checker. There is also no case for the AComprehensionRenameChannelExp node in the interpreter so it cannot be interpreted.

**Comment by joey-coleman** [comment]
I will need to review this next week; D23.x (for some value of x) defines renaming as simply substitution; I need to check what subset we agreed to implement.

**Comment by joey-coleman** [comment]
#205 has an example of use; we need this implemented in the interpreter; @lausdahl and I will talk on it at the earliest opportunity.
