### ISSUE TITLE
Simulator breaks when channel sets are defined as set comprehensions

### ISSUE THREAD

**Issue by alvarohm** [symphonytool/symphony#205]
If there is a channel set defined by a set comprehension, the simulator stops working.
Here's an example:

```
channels
    c: nat*nat
process P = begin
    @ c?x?y -> Skip
end
```

The simulator successfully executes P, but if you add the following declaration to the file

```
chansets
    aux = {|c.x | x: nat @ x = 3|}
```

the simulator gives an exception.

**Comment by joey-coleman** [comment]
Related to #201; functionality needs to be replaced.

**Comment by lausdahl** [comment]
The evaluation of comprehensions must not include type bindings of infinite types:
and thus this is not possible to interpret

```
aux = {|c.x | x: nat @ x = 3|}
```

while this is fine

```
aux = {| c.i.j | i in set {1,2}, j in set {1,2} |}
```

see https://github.com/overturetool/overture/blob/development/core/interpreter/src/main/java/org/overture/interpreter/utilities/type/AllValuesCollector.java for more info in the types supported.
(only the basic type bool can be used as shown in the code above `b:bool`)
