### ISSUE TITLE
typechecker issues reported on Save - additional trigger desirable?

### ISSUE THREAD

**Issue by RalphHains** [symphonytool/symphony#206]
I noticed that type checker level errors for CML code files are not being output (to the Problem tab) immediately after the type checker has finished running - they seem to need a trigger - saving the file will do it - perhaps for performance issues?
This can be demonstrated by pasting CML text (with type check errors or warnings) into a previously blank CML file loaded into Symphony. The type checker will run but no errors will be reported until the changes are saved. Fair enough you might think (let the poor developer finish typing).
However, this is not ideal wrt SysML to CML autogeneration - which changes the file directly on the filesystem. Symphony will then reload it (which is good) but because Symphony knows it now matches the filesystem "Save" is grey (also quite right, but now the user cannot simply press Save in order to see any errors). I guess I am asking for a reload from disk due to file change to both run the type checker (which it does) but also to trigger the errors to be output. Either that or another button to force redisplay of errors (apologies if there is one already - I don't know where it might be if so)

**Comment by lausdahl** [comment]
When a file is changed in the editor it will wait for a delay and then run the parser. The type checker (builder) is only ran when the file is saved or when the project is cleaned. A clean on a project with a changed file that has not been saved will check the file on disk (from what I remember).

To do what you are asking for:
- select the file and refresh it in the navigator (optional)
- select Project -> Clean... in the toolbar and either clean all or just the one you need

this will refresh the file parse, type check it and output all errors in the problem view.
