### ISSUE TITLE
Parser: channel name expressions does not parse a b.1.2 and b.1.2.3 correctly in channel comprehensions

### ISSUE THREAD

**Issue by lausdahl** [symphonytool/symphony#210]
The parser does something strange when parsing the following:

```
aux2 = {c.x.x | x: nat @ x = 3}
```

this parses as `c.x`, note the mising x.

A similar issue happens with `c.1.2` which gives a number `c.(1,2)`

**Comment by joey-coleman** [comment]
This example seems to work fine; we can't reproduce it even on Kenneth's machine.

The second example is related to #215.
