### ISSUE TITLE
Type Checker: Missing type check for AAlphabetisedParallelismReplicatedAction

### ISSUE THREAD

**Issue by lausdahl** [symphonytool/symphony#213]
The type checker does not type check this node! 
- How is the syntax?
- What should be checked

**Comment by joey-coleman** [comment]
Syntax is:

```
'||' replicationDeclarationList '@' '[' nameset '|' chanset ']' action
```

Check it exactly like `AInterleavingReplicatedAction`, but also check the `nameset`, so:
- vars in the `nameset` must be in scope,
- vars assigned to in the `action` not in the `nameset` should generate a warning
