### ISSUE TITLE
ProB-based set element selection for implicit functions defaults to off

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#230]
Two interpreter tests are failing:
- `standard/action/statements/interpretable-implicitfunction.cml`
- `standard/action/statements/interpretable-implicitfunction2.cml`

Both fail because they cannot apply implicit functions that do the simple selection from a set.

I suspect that the interpreter just needs to have ProB enabled for these tests.

**Comment by lausdahl** [comment]
fixed in 718dcac6e53b110758ab35b62b58c20324dad778
