### ISSUE TITLE
Multiple null's in generated POs

### ISSUE THREAD

**Issue by pglvdm** [symphonytool/symphony#239]
For the GridManager project checked into the SVN as compasssvn\Theme5\JointPapers\GM_CML\projects\GM-06 the tweltwth PO generated looks like:

```
(forall t:nat, r:map (nat) to (bool) & (null null (hold_curve <> [])))
```

**Comment by ldcouto** [comment]
Fixed in overturetool/overture@85fd99bc9d17e14626ad977c9e0cfd23d7cceb9a
