### ISSUE TITLE
Interpreter: Not all external choices offered when in parallel with another action

### ISSUE THREAD

**Issue by bandurvp** [symphonytool/symphony#242]
When animated, the following specification, only offers one choice for communication.  As written, it will offer only`a.1`.  If `(B [] A)` is changed to `(A [] B)` the only choice will be `a.2`.

```
channels
    a : int

process Test = 
begin

actions
A = a!1 -> Skip
B = a!2 -> Skip
C = a?x -> Skip

@ (B [] A) [|{a}|] C

end
```

**Comment by joey-coleman** [comment]
@lausdahl Care to guess if this is related to #235?
