### ISSUE TITLE
Browse for 'Top Process' not working in Definition of run/debug configurations

### ISSUE THREAD

**Issue by UweSchulze** [symphonytool/symphony#244]
Symphony version: Dev/0.3.1-384-g4c0a563
build from: commit 7d883acd484afa789b441c7f9aa81d472d8ebf61 [7d883ac] 
branch: uwe

When defining or adjusting a run configuration or a debug configuration of a CML project, the dialog offers the possibility to search/browse for the top process of this configuration (in tab Main). Clicking on the button "Search..." in the "Top Process" group opens a new dialog offering the list of all defined processes. This list is empty in my version.

![screen shot 2014-06-19 at 09 50 03](https://cloud.githubusercontent.com/assets/4726080/3324878/6c82d712-f786-11e3-8e7f-2f3034f11f29.png)

I did not check this with the current nightly builds or something like that, but my branch is close to development.

**Comment by lausdahl** [comment]
I'm unable to reproduce this with the following model:

```
process P = 
begin

@Skip

end
```

at 72a0b2ddae7f1f50489b84581ed7594eece166bb
