### ISSUE TITLE
Interpreter: ACompVarsetExpression case is not yet implemented at null

### ISSUE THREAD

**Issue by pglvdm** [symphonytool/symphony#249]
This happens imediately when one tries to debug the LevelCrossing case study

**Comment by lausdahl** [comment]
I need a small example of this. @pglvdm

**Comment by lausdahl** [comment]
@joey-coleman can you help give an example of this.

**Comment by lausdahl** [comment]
I'm running the `LevelCrossing` example now and it does not give any error for `ASubVOpVarsetExpression` but is does for `ACompVarsetExpression` what is this? does it exist in a similar version in VDM?

**Comment by joey-coleman** [comment]
ACompVarsetExpression should be generated in a case like:

```
channels
  a : nat

process Test = begin
@
  a.1 -> Skip [| { a.i | i in set {1,2,3} } |] a.1 -> Skip
end

/* Expected trace: 
   <a.1>
*/
```

Not all chansets/namesets need the {| |} brackets.  The presence of the bars means that the resulting names are prefixes of the whole channel name; the lack of bars means the resulting names must be complete.

**Comment by lausdahl** [comment]
I need help with the result of:
`{ a.i | i in set {1,2,3} }` what set does it generate.

There is an implementation of `AFatCompVarsetExpression` which must be similar since the node has the same fields. I expect one of them to give a more precise set (fully qualified).

**Comment by lausdahl** [comment]
I have changed this bug to only consist of the `ACompVarsetExpression` and opened a new one for `ASubVOpVarsetExpression` see #261

**Comment by pglvdm** [comment]
I believe that the result of such an expression is a set of channel names such as "a.1", "a.2" and "a.3".

**Comment by joey-coleman** [comment]
The "non-`Fat`" versions must have fully-qualified channel names, whereas the "`Fat`" versions allow the use of prefixes (and thereby include all completions relative to that prefix).

**Comment by joey-coleman** [comment]
This is probably related to #280.
A proper fix requires a fair bit of internal structure
