### ISSUE TITLE
Event selection window is not scrollable

### ISSUE THREAD

**Issue by pglvdm** [symphonytool/symphony#266]
When one is debugging and have a large list of possible events to choose from it would be handly if it would be possible to scroll in the window.

**Comment by joey-coleman** [comment]
Example:

```
channels
  a:nat
process Test = begin 
@ ||| i in set {1,...,50} @ [{}] a.i-> Skip
end
```

Note the CML Event Options window has no visible scrollbar, and we cannot scroll by other means.

![symphony debug env with non-scrollable event options window](https://cloud.githubusercontent.com/assets/1689646/3397865/bd69a052-fd26-11e3-9eb2-7e595861e8cf.png)

**Comment by joey-coleman** [comment]
Fixed in 773b2e
