### ISSUE TITLE
Model checker failing test

### ISSUE THREAD

**Issue by ldcouto** [symphonytool/symphony#272]
The model checker has only one test: `eu.compassresearch.core.analysis.modelchecker.test.TestCMLModelchecker`.

It has been failing for a very long time now. This disrupts the build process. It needs bo be addressed in one of two ways:
- if the test is not really doing anything, it should be removed
- if the test is meant to be run, it should be fixed ASAP. Failing tests cannot be a regular part of the build.

**Comment by adalbertocajueiro** [comment]
The removal of Chaos affected the model checker as well as the changes made for the last meeting in Newcastle. This problem has been fixed right now and pushed to the remote repository on branch acf.

**Comment by ldcouto** [comment]
Yep, confirmed. Model Checker test passes.
