### ISSUE TITLE
When using run the observable event history is not updated

### ISSUE THREAD

**Issue by pglvdm** [symphonytool/symphony#295]
It doesn't make much sense to use the simulate option if the "observable event history" window is not updated.

**Comment by lausdahl** [comment]
This is not reproducible. It is happens then I need the model that makes this happen otherwise I will close the bug.

**Comment by pglvdm** [comment]
This was observed with the GM example in the SVN stored as theme5/JointPapers/GM_CML/projects/GM-12.

**Comment by lausdahl** [comment]
The build: http://build.overturetool.org/symphony/test/Build-90_2014-08-29_09-18/

shows the history:
![image](https://cloud.githubusercontent.com/assets/2575418/4088533/72fcd0b0-2f5e-11e4-89aa-296bef01759d.png)
