### ISSUE TITLE
TPT: Unbalanced parenthesis in forall quantifiers

### ISSUE THREAD

**Issue by ldcouto** [symphonytool/symphony#300]
An extra parenthesis is appended at the end of the quantified expression.

Minimum example:

```
values 
b = forall x in set {} @ false
```

Yields:

```
definition "b = +|(forall x in @set {} @ false)) : @bool|+"
declare b_def [eval,evalp]
```

**Comment by ldcouto** [comment]
Did some sniffing around and in ThmExpVisitor there's a line adding a parenthesis to endBrackets:

[very long link](https://github.com/symphonytool/symphony/blob/19075641d54efcb57d202a1ef528c7f2d6b973ee/core/analysis/theoremprover/src/main/java/eu/compassresearch/core/analysis/theoremprover/visitors/string/ThmExpStringVisitor.java#L403)

I think that's the problem but I don't know why it's there so I'm leaving it to @richardpayne for now.

**Comment by richardpaynea55** [comment]
Fixed, the set bind version wasn't adding the opening parenthesis for the expression. Now generates:

definition "b = +|(forall x in @set {} @ (false)) : @bool|+"
declare b_def [eval,evalp]

which parses fine in Isabelle

**Comment by ldcouto** [comment]
Ignore the test reference. It's actually for another issue and numbers are difficult for me.
