### ISSUE TITLE
Model checker does not work on action-reference-parameter case

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#46]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/46/) on Sourceforge by [pglvdm](https://sourceforge.net/u/pglvdm/profile/), 2013-08-24 07:20:34.467000:

An error window pops up. Following one such error it is also necessary to restart the COMPASS tool

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/46/#8ccd) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-09-29 10:45:56.389000:
- **assigned_to**: Adalberto Cajueiro de Farias

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/46/#ea32) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-09-29 10:45:56.840000:

Verify that this is still present

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/46/#d7a1) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-04 15:39:12.787000:
- **Module**:  --> model-checker

**Comment by adalbertocajueiro** [comment]
Parameterised actions and processes were affected by the changes to provide infinite communications. This is a work in progress.

**Comment by joey-coleman** [comment]
Is it still necessary to restart the entire symphony tool? If so, there should be some programmatic mechanism to kill Formula and restart it.

**Comment by adalbertocajueiro** [comment]
The popup is still shown, but restart is not necessary (in any model
checker of formula chash). Formula is killed and started automatically (via
programatic mechanism).

Cheers,
Adalberto.

2014-07-02 13:22 GMT-03:00 Joey Coleman notifications@github.com:

> Is it still necessary to restart the entire symphony tool? If so, there
> should be some programmatic mechanism to kill Formula and restart it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/symphonytool/symphony/issues/46#issuecomment-47798677
> .

## 

---

Adalberto Cajueiro de Farias
Federal University of Campina Grande
Brazil

**Comment by joey-coleman** [comment]
Ok, that's fine then — the necessity to restart the entire tool was the primary concern of this bug. Closing the issue.
