### ISSUE TITLE
Model checker giver java null point exceptions for the small standard examples like BitRegister

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#74]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/74/) on Sourceforge by [pglvdm](https://sourceforge.net/u/pglvdm/profile/), 2013-09-21 08:54:11.806000:

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/74/#a501) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-09-29 10:46:57.306000:
- **assigned_to**: Adalberto Cajueiro de Farias

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/74/#3add) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-18 16:00:42.771000:
- **Module**:  --> model-checker

**Comment by adalbertocajueiro** [comment]
This bug has been fixed in version 0.3.3.
