### ISSUE TITLE
Model checker seems to deal with one file and one process at a time

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#87]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/87/) on Sourceforge by [pglvdm](https://sourceforge.net/u/pglvdm/profile/), 2013-09-30 15:08:09.414000:

It looks to me you can only start the model checker with one file (and not a project). It even seems that the file can only have one process. Surely this is just a temporary limitation!?

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/87/#375b) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-10-03 14:00:55.426000:
- **assigned_to**: Adalberto Cajueiro de Farias

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/87/#9556) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-04 15:38:59.556000:
- **Module**:  --> model-checker

**Comment by adalbertocajueiro** [comment]
There is only one instance of FORMULA running and providing support inside Symphony. Such an instance does not allow analysis of multiple files. Moreover, the analysis takes some time so it has been put only in a single file instead of a project. Also, if more than one process have been defined in a single cml file, que analysis should consider all of them. This certainly will make the model checker activity taking a long time.

**Comment by joey-coleman** [comment]
related to #254

**Comment by joey-coleman** [comment]
So, the complaint was that the mc can only be activated on a single file, and the response was that the mc can only handle small models.  That's not really an answer.

The model checker should be grabbing the AST for the whole project and translating that; it shouldn't be directly aware of the cml files at all.  If there's a restriction that the overall model can only have one process, well, that's unfortunate, but that's unrelated to how many files are in the project.

Unless you're doing something that requires parsing the CML directly (which is crazy), you should grab the typechecked AST from the project, check it against any constraints you have, transform it, and then invoke the model checker.

**Comment by adalbertocajueiro** [comment]
Actually, not small models but one single cml file (possibly huge and containing several processes). I believe that the suggestion is to make the model checker ivocation similar to the interpreter: from a selected model, it shows all processes to be animated. The user chooses one and the model checker analyses it. The model checker does not parse a CML file directly. It calls the method getParseListDefinitions() of ICmlSourceUnit, transform it and calls the model checker. This has to change to get the AST from the ICmlProject (probably the method getModel().getDefinitions()).

**Comment by joey-coleman** [comment]
Ok, so it is "just" a matter of UI engineering, which is good.  This is a definite usability concern though.

**Comment by adalbertocajueiro** [comment]
Done! Model checker menu available for a cml project.
